clear

echo "                                                                         "
echo "                                                                         "
echo "                                                                         "
echo "                                     ▄▄▄      ▓█████▄  ███▄ ▄███▓ ▄▄▄     ▄▄▄█████▓"
echo "                                    ▒████▄    ▒██▀ ██▌▓██▒▀█▀ ██▒▒████▄   ▓  ██▒ ▓▒"
echo "                                    ▒██  ▀█▄  ░██   █▌▓██    ▓██░▒██  ▀█▄ ▒ ▓██░ ▒░"
echo "                                    ░██▄▄▄▄██ ░▓█▄   ▌▒██    ▒██ ░██▄▄▄▄██░ ▓██▓ ░ "
echo "                                     ▓█   ▓██▒░▒████▓ ▒██▒   ░██▒ ▓█   ▓██▒ ▒██▒ ░ "
echo "                                     ▒▒   ▓▒█░ ▒▒▓  ▒ ░ ▒░   ░  ░ ▒▒   ▓▒█░ ▒ ░░ "
echo "                                     ▒   ▒▒ ░ ░ ▒  ▒ ░  ░      ░  ▒   ▒▒ ░   ░  "
echo "                                    ░   ▒    ░ ░  ░ ░      ░     ░   ▒    ░   "
echo "                                        ░  ░   ░           ░         ░  ░   "
echo "                                             ░     "



while :
do

  python3 /home/ubuntu/Desktop/dieu/BTC1.py &
  python3 /home/ubuntu/Desktop/dieu/ETH1.py &
  python3 /home/ubuntu/Desktop/dieu/USDT1.py &
  python3 /home/ubuntu/Desktop/dieu/BNB1.py &
  python3 /home/ubuntu/Desktop/dieu/XRP1.py &
  python3 /home/ubuntu/Desktop/dieu/BUSD1.py &
  python3 /home/ubuntu/Desktop/dieu/ADA1.py &
  python3 /home/ubuntu/Desktop/dieu/DOGE1.py &
  python3 /home/ubuntu/Desktop/dieu/MATIC1.py &
  python3 /home/ubuntu/Desktop/dieu/SOL1.py &
  python3 /home/ubuntu/Desktop/dieu/DOT1.py &
  python3 /home/ubuntu/Desktop/dieu/SHIB1.py &
  python3 /home/ubuntu/Desktop/dieu/LTC1.py &
  python3 /home/ubuntu/Desktop/dieu/TRX1.py &
  python3 /home/ubuntu/Desktop/dieu/AVAX1.py &
  python3 /home/ubuntu/Desktop/dieu/UNI1.py &
  python3 /home/ubuntu/Desktop/dieu/WBTC1.py &
  python3 /home/ubuntu/Desktop/dieu/ATOM1.py &
  python3 /home/ubuntu/Desktop/dieu/LINK1.py &
  python3 /home/ubuntu/Desktop/dieu/ETC1.py &
  python3 /home/ubuntu/Desktop/dieu/XMR1.py &
  python3 /home/ubuntu/Desktop/dieu/BCH1.py &
  python3 /home/ubuntu/Desktop/dieu/APT1.py &
  python3 /home/ubuntu/Desktop/dieu/LDO1.py &
  python3 /home/ubuntu/Desktop/dieu/XLM1.py &
  python3 /home/ubuntu/Desktop/dieu/HBAR1.py &
  python3 /home/ubuntu/Desktop/dieu/FIL1.py &
  python3 /home/ubuntu/Desktop/dieu/NEAR1.py &
  python3 /home/ubuntu/Desktop/dieu/APE1.py &
  python3 /home/ubuntu/Desktop/dieu/ALGO1.py &
  python3 /home/ubuntu/Desktop/dieu/VET1.py &
  python3 /home/ubuntu/Desktop/dieu/QNT1.py &
  python3 /home/ubuntu/Desktop/dieu/ICP1.py &
  python3 /home/ubuntu/Desktop/dieu/GRT1.py &
  python3 /home/ubuntu/Desktop/dieu/FTM1.py &
  python3 /home/ubuntu/Desktop/dieu/MANA1.py &
  python3 /home/ubuntu/Desktop/dieu/AAVE1.py &
  python3 /home/ubuntu/Desktop/dieu/EOS1.py &
  python3 /home/ubuntu/Desktop/dieu/EGLD1.py &
  python3 /home/ubuntu/Desktop/dieu/AXS1.py &
  python3 /home/ubuntu/Desktop/dieu/FLOW1.py &
  python3 /home/ubuntu/Desktop/dieu/THETA1.py &
  python3 /home/ubuntu/Desktop/dieu/SAND1.py &
  python3 /home/ubuntu/Desktop/dieu/XTZ1.py &
  python3 /home/ubuntu/Desktop/dieu/LUNC1.py &
  python3 /home/ubuntu/Desktop/dieu/IMX1.py &
  python3 /home/ubuntu/Desktop/dieu/MINA1.py &
  python3 /home/ubuntu/Desktop/dieu/CHZ1.py &
  python3 /home/ubuntu/Desktop/dieu/RPL1.py &
  python3 /home/ubuntu/Desktop/dieu/CRV1.py &
  python3 /home/ubuntu/Desktop/dieu/FXS1.py &
  python3 /home/ubuntu/Desktop/dieu/DASH1.py &
  python3 /home/ubuntu/Desktop/dieu/ZEC1.py &
  python3 /home/ubuntu/Desktop/dieu/MKR1.py &
  python3 /home/ubuntu/Desktop/dieu/BTTC1.py &
  python3 /home/ubuntu/Desktop/dieu/CAKE1.py &
  python3 /home/ubuntu/Desktop/dieu/KLAY1.py &
  python3 /home/ubuntu/Desktop/dieu/XEC1.py &
  python3 /home/ubuntu/Desktop/dieu/GMX1.py &
  python3 /home/ubuntu/Desktop/dieu/IOTA1.py &
  python3 /home/ubuntu/Desktop/dieu/SNX1.py &
  python3 /home/ubuntu/Desktop/dieu/NEO1.py &
  python3 /home/ubuntu/Desktop/dieu/TWT1.py &
  python3 /home/ubuntu/Desktop/dieu/OP1.py &
  python3 /home/ubuntu/Desktop/dieu/RUNE1.py &
  python3 /home/ubuntu/Desktop/dieu/LRC1.py &
  python3 /home/ubuntu/Desktop/dieu/FTT1.py &
  python3 /home/ubuntu/Desktop/dieu/AGIX1.py &
  python3 /home/ubuntu/Desktop/dieu/PAXG1.py &
  python3 /home/ubuntu/Desktop/dieu/OSMO1.py &
  python3 /home/ubuntu/Desktop/dieu/ZIL1.py &
  python3 /home/ubuntu/Desktop/dieu/BNX1.py &
  python3 /home/ubuntu/Desktop/dieu/CVX1.py &
  python3 /home/ubuntu/Desktop/dieu/ROSE1.py &
  python3 /home/ubuntu/Desktop/dieu/ROSE1.py &
  python3 /home/ubuntu/Desktop/dieu/RNDR1.py &
  python3 /home/ubuntu/Desktop/dieu/ENJ1.py &
  python3 /home/ubuntu/Desktop/dieu/BAT1.py &
  python3 /home/ubuntu/Desktop/dieu/STX1.py &
  python3 /home/ubuntu/Desktop/dieu/DYDX1.py &
  python3 /home/ubuntu/Desktop/dieu/1INCH1.py &
  python3 /home/ubuntu/Desktop/dieu/LUNA1.py &
  python3 /home/ubuntu/Desktop/dieu/NEXO1.py &
  python3 /home/ubuntu/Desktop/dieu/ASTR1.py &
  python3 /home/ubuntu/Desktop/dieu/AR1.py &
  python3 /home/ubuntu/Desktop/dieu/CELO1.py &
  python3 /home/ubuntu/Desktop/dieu/HOT1.py &
  python3 /home/ubuntu/Desktop/dieu/KAVA1.py &
  python3 /home/ubuntu/Desktop/dieu/MAGIC1.py &
  python3 /home/ubuntu/Desktop/dieu/COMP1.py &
  python3 /home/ubuntu/Desktop/dieu/RVN1.py &
  python3 /home/ubuntu/Desktop/dieu/FET1.py &
  python3 /home/ubuntu/Desktop/dieu/WOO1.py &
  python3 /home/ubuntu/Desktop/dieu/HNT1.py &
  python3 /home/ubuntu/Desktop/dieu/DCR1.py &
  python3 /home/ubuntu/Desktop/dieu/XEM1.py &
  python3 /home/ubuntu/Desktop/dieu/T1.py &
  python3 /home/ubuntu/Desktop/dieu/TFUEL1.py &
  python3 /home/ubuntu/Desktop/dieu/SSV1.py &
  python3 /home/ubuntu/Desktop/dieu/BAL1.py &
  sleep 10
  python3 /home/ubuntu/Desktop/dieu/BAL1.py &
  python3 /home/ubuntu/Desktop/dieu/ONE1.py &
  python3 /home/ubuntu/Desktop/dieu/GALA1.py &
  python3 /home/ubuntu/Desktop/dieu/JASMY1.py &
  python3 /home/ubuntu/Desktop/dieu/SUSHI1.py &
  python3 /home/ubuntu/Desktop/dieu/ENS1.py &
  python3 /home/ubuntu/Desktop/dieu/USTC1.py &
  python3 /home/ubuntu/Desktop/dieu/OCEAN1.py &
  python3 /home/ubuntu/Desktop/dieu/KSM1.py &
  python3 /home/ubuntu/Desktop/dieu/IOTX1.py &
  python3 /home/ubuntu/Desktop/dieu/ANKR1.py &
  python3 /home/ubuntu/Desktop/dieu/QTUM1.py &
  python3 /home/ubuntu/Desktop/dieu/GMT1.py &
  python3 /home/ubuntu/Desktop/dieu/AUDIO1.py &
  python3 /home/ubuntu/Desktop/dieu/INJWAVES1.py &
  python3 /home/ubuntu/Desktop/dieu/YFI1.py &
  python3 /home/ubuntu/Desktop/dieu/MASK1.py &
  python3 /home/ubuntu/Desktop/dieu/GLMR1.py &
  python3 /home/ubuntu/Desktop/dieu/LPT1.py &
  python3 /home/ubuntu/Desktop/dieu/GLM1.py &
  python3 /home/ubuntu/Desktop/dieu/JST1.py &
  python3 /home/ubuntu/Desktop/dieu/KDA1.py &
  python3 /home/ubuntu/Desktop/dieu/BAND1.py &
  python3 /home/ubuntu/Desktop/dieu/FLUX1.py &
  python3 /home/ubuntu/Desktop/dieu/SC1.py &
  python3 /home/ubuntu/Desktop/dieu/OMG1.py &
  python3 /home/ubuntu/Desktop/dieu/SKL1.py &
  python3 /home/ubuntu/Desktop/dieu/ICX1.py &
  python3 /home/ubuntu/Desktop/dieu/ZRX1.py &
  python3 /home/ubuntu/Desktop/dieu/HIVE1.py &
  python3 /home/ubuntu/Desktop/dieu/AMP1.py &
  python3 /home/ubuntu/Desktop/dieu/ONT1.py &
  python3 /home/ubuntu/Desktop/dieu/IOST1.py &
  python3 /home/ubuntu/Desktop/dieu/RSR1.py &
  python3 /home/ubuntu/Desktop/dieu/SFP1.py &
  python3 /home/ubuntu/Desktop/dieu/SXP1.py &
  python3 /home/ubuntu/Desktop/dieu/ZEN1.py &
  python3 /home/ubuntu/Desktop/dieu/ILV1.py &
  python3 /home/ubuntu/Desktop/dieu/WAXP1.py &
  python3 /home/ubuntu/Desktop/dieu/BICO1.py &
  python3 /home/ubuntu/Desktop/dieu/RLC1.py &
  python3 /home/ubuntu/Desktop/dieu/CFX1.py &
  python3 /home/ubuntu/Desktop/dieu/STORJ1.py &
  python3 /home/ubuntu/Desktop/dieu/SYS1.py &
  python3 /home/ubuntu/Desktop/dieu/DGB1.py &
  python3 /home/ubuntu/Desktop/dieu/CKB1.py &
  python3 /home/ubuntu/Desktop/dieu/CELR1.py &
  python3 /home/ubuntu/Desktop/dieu/VGX1.py &
  python3 /home/ubuntu/Desktop/dieu/PEOPLE1.py &
  python3 /home/ubuntu/Desktop/dieu/STG1.py &
  python3 /home/ubuntu/Desktop/dieu/LSK1.py &
  python3 /home/ubuntu/Desktop/dieu/UMA1.py &
  python3 /home/ubuntu/Desktop/dieu/HOOK1.py &
  python3 /home/ubuntu/Desktop/dieu/CHR1.py &
  python3 /home/ubuntu/Desktop/dieu/KNC1.py &
  python3 /home/ubuntu/Desktop/dieu/SCRT1.py &
  python3 /home/ubuntu/Desktop/dieu/ELF1.py &
  python3 /home/ubuntu/Desktop/dieu/HFT1.py &
  python3 /home/ubuntu/Desktop/dieu/SLP1.py &
  python3 /home/ubuntu/Desktop/dieu/PLA1.py &
  python3 /home/ubuntu/Desktop/dieu/API31.py &
  python3 /home/ubuntu/Desktop/dieu/PUNDIX1.py &
  python3 /home/ubuntu/Desktop/dieu/MOB1.py &
  python3 /home/ubuntu/Desktop/dieu/NMR1.py &
  python3 /home/ubuntu/Desktop/dieu/GAL1.py &
  python3 /home/ubuntu/Desktop/dieu/XNO1.py &
  python3 /home/ubuntu/Desktop/dieu/MC1.py &
  python3 /home/ubuntu/Desktop/dieu/ANT1.py &
  python3 /home/ubuntu/Desktop/dieu/GTC1.py &
  python3 /home/ubuntu/Desktop/dieu/SNT1.py &
  python3 /home/ubuntu/Desktop/dieu/GFT1.py &
  python3 /home/ubuntu/Desktop/dieu/CVC1.py &
  python3 /home/ubuntu/Desktop/dieu/COTI1.py &
  python3 /home/ubuntu/Desktop/dieu/POLYX1.py &
  python3 /home/ubuntu/Desktop/dieu/CTSI1.py &
  python3 /home/ubuntu/Desktop/dieu/PYR1.py &
  python3 /home/ubuntu/Desktop/dieu/DUSK1.py &
  python3 /home/ubuntu/Desktop/dieu/REQ1.py &
  python3 /home/ubuntu/Desktop/dieu/DEXE1.py &
  python3 /home/ubuntu/Desktop/dieu/ONG1.py &
  python3 /home/ubuntu/Desktop/dieu/STEEM1.py &
  python3 /home/ubuntu/Desktop/dieu/HIGH1.py &
  python3 /home/ubuntu/Desktop/dieu/ARDR1.py &
  python3 /home/ubuntu/Desktop/dieu/ALPHA1.py &
  python3 /home/ubuntu/Desktop/dieu/DENT1.py &
  python3 /home/ubuntu/Desktop/dieu/RAD1.py &
  python3 /home/ubuntu/Desktop/dieu/PHA1.py &
  python3 /home/ubuntu/Desktop/dieu/POWR1.py &
  python3 /home/ubuntu/Desktop/dieu/SRM1.py &
  python3 /home/ubuntu/Desktop/dieu/MBOX1.py &
  python3 /home/ubuntu/Desktop/dieu/PROM1.py &
  python3 /home/ubuntu/Desktop/dieu/SPELL1.py &
  python3 /home/ubuntu/Desktop/dieu/IQ1.py &
  python3 /home/ubuntu/Desktop/dieu/REN1.py &
  python3 /home/ubuntu/Desktop/dieu/MDX1.py &
  python3 /home/ubuntu/Desktop/dieu/WIN1.py &
  python3 /home/ubuntu/Desktop/dieu/ACH1.py &
  python3 /home/ubuntu/Desktop/dieu/XVS1.py &
  python3 /home/ubuntu/Desktop/dieu/NKN1.py &
  python3 /home/ubuntu/Desktop/dieu/STRAX1.py &
  sleep 10
  python3 /home/ubuntu/Desktop/dieu/STRAX1.py &
  python3 /home/ubuntu/Desktop/dieu/XRPUP1.py &
  python3 /home/ubuntu/Desktop/dieu/XRPDOWN1.py &
  python3 /home/ubuntu/Desktop/dieu/MULTI1.py &
  python3 /home/ubuntu/Desktop/dieu/LINKUP1.py &
  python3 /home/ubuntu/Desktop/dieu/LINKDOWN1.py &
  python3 /home/ubuntu/Desktop/dieu/HIFI1.py &
  python3 /home/ubuntu/Desktop/dieu/GBP1.py &
  python3 /home/ubuntu/Desktop/dieu/EUR1.py &
  python3 /home/ubuntu/Desktop/dieu/ETHUP1.py &
  python3 /home/ubuntu/Desktop/dieu/ETHDOWN1.py &
  python3 /home/ubuntu/Desktop/dieu/BTCUP1.py &
  python3 /home/ubuntu/Desktop/dieu/BTCDOWN1.py &
  python3 /home/ubuntu/Desktop/dieu/BNBUP1.py &
  python3 /home/ubuntu/Desktop/dieu/BNBDOWN1.py &
  python3 /home/ubuntu/Desktop/dieu/BETH1.py &
  python3 /home/ubuntu/Desktop/dieu/AUD1.py &
  python3 /home/ubuntu/Desktop/dieu/ADAP1.py &
  python3 /home/ubuntu/Desktop/dieu/ADADOWN1.py &
  python3 /home/ubuntu/Desktop/dieu/JUV1.py &
  python3 /home/ubuntu/Desktop/dieu/OG1.py &
  python3 /home/ubuntu/Desktop/dieu/PERL1.py &
  python3 /home/ubuntu/Desktop/dieu/ATM1.py &
  python3 /home/ubuntu/Desktop/dieu/UFT1.py &
  python3 /home/ubuntu/Desktop/dieu/CVP1.py &
  python3 /home/ubuntu/Desktop/dieu/PNT1.py &
  python3 /home/ubuntu/Desktop/dieu/ACM1.py &
  python3 /home/ubuntu/Desktop/dieu/MIR1.py &
  python3 /home/ubuntu/Desktop/dieu/TORN1.py &
  python3 /home/ubuntu/Desktop/dieu/OAX1.py &
  python3 /home/ubuntu/Desktop/dieu/WABI1.py &
  python3 /home/ubuntu/Desktop/dieu/AKRO1.py &
  python3 /home/ubuntu/Desktop/dieu/FOR1.py &
  python3 /home/ubuntu/Desktop/dieu/PROS1.py &
  python3 /home/ubuntu/Desktop/dieu/ANC1.py &
  python3 /home/ubuntu/Desktop/dieu/DREP1.py &
  python3 /home/ubuntu/Desktop/dieu/AST1.py &
  python3 /home/ubuntu/Desktop/dieu/VIB1.py &
  python3 /home/ubuntu/Desktop/dieu/DF1.py &
  python3 /home/ubuntu/Desktop/dieu/WTC1.py &
  python3 /home/ubuntu/Desktop/dieu/OOKI1.py &
  python3 /home/ubuntu/Desktop/dieu/DOCK1.py &
  python3 /home/ubuntu/Desktop/dieu/AION1.py &
  python3 /home/ubuntu/Desktop/dieu/FIDA1.py &
  python3 /home/ubuntu/Desktop/dieu/KEY1.py &
  python3 /home/ubuntu/Desktop/dieu/FRONT1.py &
  python3 /home/ubuntu/Desktop/dieu/EPX1.py &
  python3 /home/ubuntu/Desktop/dieu/AMB1.py &
  python3 /home/ubuntu/Desktop/dieu/CREAM1.py &
  python3 /home/ubuntu/Desktop/dieu/VITE1.py &
  python3 /home/ubuntu/Desktop/dieu/PORTO1.py &
  python3 /home/ubuntu/Desktop/dieu/OM1.py &
  python3 /home/ubuntu/Desktop/dieu/BURGER1.py &
  python3 /home/ubuntu/Desktop/dieu/AUTO1.py &
  python3 /home/ubuntu/Desktop/dieu/HARD1.py &
  python3 /home/ubuntu/Desktop/dieu/WING1.py &
  python3 /home/ubuntu/Desktop/dieu/FARM1.py &
  python3 /home/ubuntu/Desktop/dieu/PSG1.py &
  python3 /home/ubuntu/Desktop/dieu/ADX1.py &
  python3 /home/ubuntu/Desktop/dieu/TROY1.py &
  python3 /home/ubuntu/Desktop/dieu/COS1.py &
  python3 /home/ubuntu/Desktop/dieu/CITY1.py &
  python3 /home/ubuntu/Desktop/dieu/SANTOS1.py &
  python3 /home/ubuntu/Desktop/dieu/QLS1.py &
  python3 /home/ubuntu/Desktop/dieu/POLS1.py &
  python3 /home/ubuntu/Desktop/dieu/ALPACA1.py &
  python3 /home/ubuntu/Desktop/dieu/PHB1.py &
  python3 /home/ubuntu/Desktop/dieu/SNM1.py &
  python3 /home/ubuntu/Desktop/dieu/TRU1.py &
  python3 /home/ubuntu/Desktop/dieu/PERP1.py &
  python3 /home/ubuntu/Desktop/dieu/WAN1.py &
  python3 /home/ubuntu/Desktop/dieu/LTO1.py &
  python3 /home/ubuntu/Desktop/dieu/DEGO1.py &
  python3 /home/ubuntu/Desktop/dieu/AUCTION1.py &
  python3 /home/ubuntu/Desktop/dieu/BOND1.py &
  python3 /home/ubuntu/Desktop/dieu/BIFI1.py &
  python3 /home/ubuntu/Desktop/dieu/KMD1.py &
  python3 /home/ubuntu/Desktop/dieu/ALPINE1.py &
  python3 /home/ubuntu/Desktop/dieu/TOMO1.py &
  python3 /home/ubuntu/Desktop/dieu/ALCX1.py &
  python3 /home/ubuntu/Desktop/dieu/IDEX1.py &
  python3 /home/ubuntu/Desktop/dieu/DIA1.py &
  python3 /home/ubuntu/Desktop/dieu/REI1.py &
  python3 /home/ubuntu/Desktop/dieu/LEVER1.py &
  python3 /home/ubuntu/Desktop/dieu/FIS1.py &
  python3 /home/ubuntu/Desktop/dieu/LINA1.py &
  python3 /home/ubuntu/Desktop/dieu/MDT1.py &
  python3 /home/ubuntu/Desktop/dieu/AGLD1.py &
  python3 /home/ubuntu/Desktop/dieu/QI1.py &
  python3 /home/ubuntu/Desktop/dieu/VIDT1.py &
  python3 /home/ubuntu/Desktop/dieu/AVA1.py &
  python3 /home/ubuntu/Desktop/dieu/ERN1.py &
  python3 /home/ubuntu/Desktop/dieu/BTS1.py &
  python3 /home/ubuntu/Desktop/dieu/KP3R1.py &
  python3 /home/ubuntu/Desktop/dieu/CLV1.py &
  python3 /home/ubuntu/Desktop/dieu/CHESS1.py &
  python3 /home/ubuntu/Desktop/dieu/ORN1.py &
  python3 /home/ubuntu/Desktop/dieu/BLZ1.py &
  python3 /home/ubuntu/Desktop/dieu/VOXEL1.py &
  python3 /home/ubuntu/Desktop/dieu/PIVX1.py &
  sleep 10
  python3 /home/ubuntu/Desktop/dieu/PIVX1.py &
  python3 /home/ubuntu/Desktop/dieu/GAS1.py &
  python3 /home/ubuntu/Desktop/dieu/FIRO1.py &
  python3 /home/ubuntu/Desktop/dieu/NEBL1.py &
  python3 /home/ubuntu/Desktop/dieu/BAR1.py &
  python3 /home/ubuntu/Desktop/dieu/DATA1.py &
  python3 /home/ubuntu/Desktop/dieu/QUICK1.py &
  python3 /home/ubuntu/Desktop/dieu/LAZIO1.py &
  python3 /home/ubuntu/Desktop/dieu/BEL1.py &
  python3 /home/ubuntu/Desktop/dieu/UNFI1.py &
  python3 /home/ubuntu/Desktop/dieu/IRIS1.py &
  python3 /home/ubuntu/Desktop/dieu/NULS1.py &
  python3 /home/ubuntu/Desktop/dieu/TRB1.py &
  python3 /home/ubuntu/Desktop/dieu/FIO1.py &
  python3 /home/ubuntu/Desktop/dieu/POND1.py &
  python3 /home/ubuntu/Desktop/dieu/JOE1.py &
  python3 /home/ubuntu/Desktop/dieu/VTHO1.py &
  python3 /home/ubuntu/Desktop/dieu/ACA1.py &
  python3 /home/ubuntu/Desktop/dieu/BSW1.py &
  python3 /home/ubuntu/Desktop/dieu/FUN1.py &
  python3 /home/ubuntu/Desktop/dieu/ALICE1.py &
  python3 /home/ubuntu/Desktop/dieu/TLM1.py &
  python3 /home/ubuntu/Desktop/dieu/CTK1.py &
  python3 /home/ubuntu/Desktop/dieu/WRX1.py &
  python3 /home/ubuntu/Desktop/dieu/OGN1.py &
  python3 /home/ubuntu/Desktop/dieu/REEF1.py &
  python3 /home/ubuntu/Desktop/dieu/BNT1.py &
  python3 /home/ubuntu/Desktop/dieu/DAR1.py &
  python3 /home/ubuntu/Desktop/dieu/QKC1.py &
  python3 /home/ubuntu/Desktop/dieu/MTL1.py &
  python3 /home/ubuntu/Desktop/dieu/OXT1.py &
  python3 /home/ubuntu/Desktop/dieu/STMX1.py &
  python3 /home/ubuntu/Desktop/dieu/DODO1.py &
  python3 /home/ubuntu/Desktop/dieu/BETA1.py &
  python3 /home/ubuntu/Desktop/dieu/ATA1.py &
  python3 /home/ubuntu/Desktop/dieu/C981.py &
  python3 /home/ubuntu/Desktop/dieu/ARK1.py &
  python3 /home/ubuntu/Desktop/dieu/FORTH1.py &
  python3 /home/ubuntu/Desktop/dieu/RIF1.py &
  python3 /home/ubuntu/Desktop/dieu/YGG1.py &
  python3 /home/ubuntu/Desktop/dieu/LOOM1.py &
  python3 /home/ubuntu/Desktop/dieu/UTK1.py &
  python3 /home/ubuntu/Desktop/dieu/AERGO1.py &
  python3 /home/ubuntu/Desktop/dieu/MBL1.py &
  python3 /home/ubuntu/Desktop/dieu/SUN1.py &
  python3 /home/ubuntu/Desktop/dieu/BADGER1.py &
  python3 /home/ubuntu/Desktop/dieu/SUPER1.py &
  python3 /home/ubuntu/Desktop/dieu/MOVR1.py &
  python3 /home/ubuntu/Desktop/dieu/CTXC1.py &
  python3 /home/ubuntu/Desktop/dieu/RARE1.py &
  python3 /home/ubuntu/Desktop/dieu/TKO1.py &
  python3 /home/ubuntu/Desktop/dieu/RAY1.py &
  python3 /home/ubuntu/Desktop/dieu/XVG1.py &
  python3 /home/ubuntu/Desktop/dieu/LIT1.py &
  python3 /home/ubuntu/Desktop/dieu/COCOS1.py &
  python3 /home/ubuntu/Desktop/dieu/WNXM1.py &
  python3 /home/ubuntu/Desktop/dieu/ARPA1.py &
  python3 /home/ubuntu/Desktop/dieu/GHST1.py &
  python3 /home/ubuntu/Desktop/dieu/MLN1.py &
  python3 /home/ubuntu/Desktop/dieu/BAKE1.py &
  python3 /home/ubuntu/Desktop/dieu/YFII1.py &
  python3 /home/ubuntu/Desktop/dieu/TVK1.py &
  python3 /home/ubuntu/Desktop/dieu/FLM1.py &
  python3 /home/ubuntu/Desktop/dieu/LOKA1.py &

clear
done
